# Generated by scripts/render-formula.ts from packaging/homebrew/amc.rb.tmpl in
# dannyhawkins/agent-mission-control. Edits here are overwritten by the next release.
class Amc < Formula
  desc "Every Claude Code session on one screen, with decisions answered from the floor"
  homepage "https://github.com/dannyhawkins/agent-mission-control"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dannyhawkins/agent-mission-control/releases/download/v0.1.0/amc-0.1.0-darwin-arm64.tar.gz"
      sha256 "fec81506b21b0cc31248b4a20474e880d74edc55fca1f8685854436385842151"
    end
    on_intel do
      url "https://github.com/dannyhawkins/agent-mission-control/releases/download/v0.1.0/amc-0.1.0-darwin-x64.tar.gz"
      sha256 "72aaf03ff98451094581f5fca1a155635c66e3bf7b99add6160efa0214470be3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dannyhawkins/agent-mission-control/releases/download/v0.1.0/amc-0.1.0-linux-arm64.tar.gz"
      sha256 "456bf3e3e58ef6e33e382484cd14e23dfa4442648a411870b3ec1ad36897f29b"
    end
    on_intel do
      url "https://github.com/dannyhawkins/agent-mission-control/releases/download/v0.1.0/amc-0.1.0-linux-x64.tar.gz"
      sha256 "15fdb0766c5f22fd2c37da442afa13f339a48cd64b517da0046e5248357da5bc"
    end
  end

  def install
    bin.install "amc"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/amc --version")
  end
end
